spring:
  application:
    name: quadstore

  flyway:
    schemas: quadstore

  jackson:
    default-property-inclusion: NON_NULL

  dataSource:
    url: jdbc:postgresql://localhost:5432/quadstore
    username: quadsmgr
    password: quadsmgr
    hikari:
      maxIdle: 10
      maxActive: 50
      maxWait: 10000