spring:
  application:
    name: quadstore

  flyway:
    schemas: quadstore

  jackson:
    default-property-inclusion: NON_NULL

  dataSource:
    url: jdbc:postgresql://localhost:5432/quadstore
    username: quadsmgr
    password: quadsmgr
    hikari:
      maxIdle: 10
      maxActive: 50
      maxWait: 10000

# Logging Properties
logging:
  level:
    org.ehcache: info
    org.jooq: info
    org.jooq.Constants: warn
    org.springframework: info
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%X]){faint} %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'

server:
  host: localhost
  port: 8080